INSERT INTO car VALUES (DEFAULT, '#1 Rimac Nevera','1.85secs','1,888','2023','2.2 Million Dollars','rimac.jpg','Rimac Nevera: A luxurious and sleek electric hypercar with incredible acceleration, top speed, and range. It boasts a 1,914 horsepower electric powertrain and can reach 60 mph in under two seconds.');
INSERT INTO car VALUES (DEFAULT, '#2 Lucid Air Sapphire','1.89secs','800','2023','249,000','lucid.jpg','Lucid Air Sapphire: A luxurious and high-performance electric sedan with a sleek and aerodynamic design. It features an advanced electric powertrain with up to 1,080 horsepower and a range of up to 520 miles on a single charge.');
INSERT INTO car VALUES (DEFAULT, '#3 Pininfarina Battista','1.9secs','1,873','2022','2.2 Million Dollars','pini.jpg','Pininfarina Battista: A stunning and exclusive electric hypercar with a sleek and futuristic design. It boasts a 1,900 horsepower electric powertrain and can reach 60 mph in under two seconds.');
INSERT INTO car VALUES (DEFAULT, '#4 Tesla Model S Plaid','1.98secs','1,006','2023','115,000','tesla.jpg','Tesla Model S Plaid: A high-performance electric sedan with a futuristic design and advanced technology. It features a tri-motor electric powertrain with up to 1,020 horsepower and a range of up to 390 miles on a single charge.');
INSERT INTO car VALUES (DEFAULT, '#5 Ultima RS LT5','2.3secs','1,200','2022','120,000','ultimars.jpg','Ultima RS LT5: A lightweight and high-performance supercar with a sleek and aerodynamic design. It features a powerful 6.2-liter V8 engine with up to 1,200 horsepower and can reach 60 mph in under 2.3 seconds.');
INSERT INTO car VALUES (DEFAULT, '#6 Dodge Challenger SRT Demon','2.3secs','829','2022','500,000','demon.jpg','Dodge Challenger SRT Demon: A powerful and aggressive muscle car with a retro-inspired design. It features a supercharged 6.2-liter V8 engine with up to 840 horsepower and can reach 60 mph in under 2.3 seconds.');
INSERT INTO car VALUES (DEFAULT, '#7 Bugatti Chiron Super Sport','2.4secs','1,578','2022','3.8 Million Dollars','bugatti.jpg','Bugatti Chiron Super Sport: A luxurious and exclusive hypercar with a sleek and aerodynamic design. It boasts a quad-turbocharged 8.0-liter W16 engine with up to 1,578 horsepower and can reach speeds of over 300 mph.');
INSERT INTO car VALUES (DEFAULT, '#8 Koenigsegg Jesko','2.5secs','1,600','2022','3.4 Million Dollars','Koeg.jpg','Koenigsegg Jesko: A powerful and exclusive hypercar with a sleek and aerodynamic design. It features a twin-turbocharged 5.0-liter V8 engine with up to 1,600 horsepower and can reach speeds of over 300 mph.');
INSERT INTO car VALUES (DEFAULT, '#9 Ferrari SF90 Stradale','2.5secs','769','2023','500,000','ferrari.jpg','Ferrari SF90 Stradale: A high-performance hybrid supercar with a sleek and aerodynamic design. It features a hybrid electric powertrain with up to 986 horsepower and can reach 60 mph in under 2.5 seconds.');
INSERT INTO car VALUES (DEFAULT, '#10 Hennessey Venom F5','2.6secs','1,792','2023','2.7 Million Dollars','Venom.jpg','Hennessey Venom F5: A powerful and exclusive hypercar with a sleek and aerodynamic design. It features a twin-turbocharged 6.6-liter V8 engine with up to 1,817 horsepower and can reach speeds of over 311 mph.');
INSERT INTO car VALUES (DEFAULT, '#11 Porsche 911 Turbo S','2.7secs','640','2023','182,000','p911.jpg','Porsche 911 Turbo S: A high-performance sports car with a sleek and iconic design. It features a twin-turbocharged 3.8-liter flat-six engine with up to 640 horsepower and can reach 60 mph in under 2.6 seconds.');
INSERT INTO car VALUES (DEFAULT, '#12 Radical RXC GT','2.7secs','400','2017','115,000','rxc.jpg','Radical RXC GT: A lightweight and high-performance sports car with a sleek and aerodynamic design. It features a powerful 3.5-liter V6 engine with up to 600 horsepower and can reach 60 mph in under 3.0 seconds.');
INSERT INTO car VALUES (DEFAULT, '#13 Lamborghini Countach LPI 800-4','2.8secs','803','2022','2.6 Million Dollars','lambo.jpg','Lamborghini Countach LPI 800-4: A limited-edition and exclusive hypercar with a sleek and iconic design. It features a hybrid electric powertrain with up to 803 horsepower and can reach 60 mph in under 2.8 seconds.');
INSERT INTO car VALUES (DEFAULT, '#14 Ariel Atom 4','2.8secs','320','2020','52,119','arielatom.jpg','Ariel Atom 4: A lightweight and high-performance sports car with a minimalist and aerodynamic design. It features a powerful 2.0-liter four-cylinder engine with up to 320 horsepower and can reach 60 mph in under 2.8 seconds.');
INSERT INTO car VALUES (DEFAULT, '#15 Porsche Taycan Turbo S','2.8secs','616','2023','190,000','ptaycan.jpg','Porsche Taycan Turbo S: A luxurious and high-performance electric sedan with a sleek and modern design. It features an advanced electric powertrain with up to 750 horsepower and a range of up to');

INSERT INTO users VALUES (DEFAULT, 'dan.wells@cornerstone.edu','$2y$10$j9gtDo09azPDDrIZwxLcV.nefQHKe..bxo1xohZR6ZhO5vHwiGc.K', TRUE, TRUE);
INSERT INTO users VALUES (DEFAULT, 'alejandro.santana@cornerstone.edu','$2y$10$j9gtDo09azPDDrIZwxLcV.nefQHKe..bxo1xohZR6ZhO5vHwiGc.K', TRUE, FALSE);
